# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: 0 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Script
        run: python3 main.py
      - name: Commit File
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: daily update
          branch: ${{ github.head_ref }}
